# Generated by Django 5.0.1 on 2024-02-16 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('posts', models.IntegerField(null=True)),
                ('followers', models.IntegerField(null=True)),
                ('following', models.IntegerField(null=True)),
                ('threads', models.TextField(blank=True, null=True)),
                ('authentication', models.TextField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('tag_id', models.TextField(blank=True, null=True)),
                ('tag_length', models.IntegerField(blank=True, null=True)),
                ('highlight_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(null=True)),
                ('like', models.IntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('tag_length', models.IntegerField(null=True)),
                ('user_tags', models.TextField(blank=True, null=True)),
                ('comment_most_like', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('content_type', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='django_piium_insta_api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reels_view', models.IntegerField(null=True)),
                ('reels_like', models.IntegerField(null=True)),
                ('reels_caption', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='django_piium_insta_api.profile')),
            ],
        ),
    ]
