# Generated by Django 5.0.1 on 2024-02-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reels',
            old_name='profile',
            new_name='profiles',
        ),
    ]
