# Generated by Django 5.0.1 on 2024-02-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
