# Generated by Django 5.0.1 on 2024-02-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0002_post_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='post_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
