# Generated by Django 5.0.1 on 2024-01-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0002_alter_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
