# Generated by Django 5.0.1 on 2024-02-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='highlight_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='posts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_profile_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag_length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
