# Generated by Django 5.0.1 on 2024-02-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0003_alter_post_comment_most_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
