# Generated by Django 5.0.1 on 2024-02-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0003_rename_profiles_reels_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='reels_date',
            field=models.IntegerField(null=True),
        ),
    ]
