# Generated by Django 5.0.1 on 2024-02-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0004_post_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authentication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='threads',
            field=models.TextField(blank=True, null=True),
        ),
    ]
