# Generated by Django 5.0.1 on 2024-02-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0006_profile_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduction_tag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tag_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
