# Generated by Django 5.0.1 on 2024-02-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0007_profile_introduction_tag_profile_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='introduction_tag',
            new_name='tag_length',
        ),
    ]
