# Generated by Django 5.0.1 on 2024-02-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0009_post_content_type_post_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='reels_comment_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reels',
            name='reels_like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reels',
            name='reels_view',
            field=models.IntegerField(null=True),
        ),
    ]
