# Generated by Django 5.0.1 on 2024-02-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_piium_insta_api', '0010_reels_reels_comment_count_reels_reels_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='reels_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
