from .get_insta_posts import *
from .get_insta_followers import *
from .get_insta_following import *
from .get_insta_date import *
from .get_insta_like import *
from .get_insta_content import *
from .get_insta_tags import *
from .get_insta_tags_length import *
from .get_insta_user_tags import *
from .get_insta_comment_most_like import *
from .login_insta_admin import *
from .searching_insta_account import *